/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tgsUas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.LayoutManager;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;

/**
 *
 * @author MOZART-PC
 */
public class frmUtama extends javax.swing.JFrame {

    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();
        subMaster.setVisible(false);
        subTrans.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        scrollSide = new javax.swing.JScrollPane();
        spBg = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmdMenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmdMaster = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmdTransaksi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmdMaster2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cmdMaster3 = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdExit = new javax.swing.JButton();
        bgForm = new javax.swing.JPanel();
        subMaster = new javax.swing.JPanel();
        mnuSupplier = new javax.swing.JButton();
        mnuBarang = new javax.swing.JButton();
        subTrans = new javax.swing.JPanel();
        mnuSupplier1 = new javax.swing.JButton();
        mnuBarang1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setMaximumSize(new java.awt.Dimension(32767, 100));
        bg.setPreferredSize(new java.awt.Dimension(728, 100));
        bg.setLayout(new java.awt.BorderLayout());

        sidePanel.setBackground(new java.awt.Color(92, 121, 168));
        sidePanel.setPreferredSize(new java.awt.Dimension(180, 395));

        scrollSide.setBackground(new java.awt.Color(92, 121, 168));
        scrollSide.setOpaque(false);

        spBg.setBackground(new java.awt.Color(92, 121, 168));
        spBg.setPreferredSize(new java.awt.Dimension(161, 400));

        pnlLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlLogo.setOpaque(false);
        pnlLogo.setPreferredSize(new java.awt.Dimension(174, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Source Code\\Icons_Images\\Image\\RnD-Logo150.png")); // NOI18N

        cmdMenu.setIcon(new javax.swing.ImageIcon("E:\\Source Code\\Icons_Images\\Image\\Menu-16.png")); // NOI18N
        cmdMenu.setBorderPainted(false);
        cmdMenu.setContentAreaFilled(false);
        cmdMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdMenuMouseExited(evt);
            }
        });
        cmdMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addComponent(cmdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cmdMaster.setBackground(new java.awt.Color(92, 121, 168));
        cmdMaster.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdMaster.setText("Master Data");
        cmdMaster.setContentAreaFilled(false);
        cmdMaster.setPreferredSize(new java.awt.Dimension(101, 32));
        cmdMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdMasterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdMasterMouseExited(evt);
            }
        });
        cmdMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMasterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cmdMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cmdTransaksi.setBackground(new java.awt.Color(92, 121, 168));
        cmdTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdTransaksi.setText("Transaksi");
        cmdTransaksi.setContentAreaFilled(false);
        cmdTransaksi.setPreferredSize(new java.awt.Dimension(101, 32));
        cmdTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdTransaksiMouseExited(evt);
            }
        });
        cmdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cmdTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        cmdMaster2.setBackground(new java.awt.Color(92, 121, 168));
        cmdMaster2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdMaster2.setText("Laporan");
        cmdMaster2.setContentAreaFilled(false);
        cmdMaster2.setPreferredSize(new java.awt.Dimension(101, 32));
        cmdMaster2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdMaster2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdMaster2MouseExited(evt);
            }
        });
        cmdMaster2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMaster2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cmdMaster2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdMaster2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        cmdMaster3.setBackground(new java.awt.Color(92, 121, 168));
        cmdMaster3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdMaster3.setText("Connect");
        cmdMaster3.setContentAreaFilled(false);
        cmdMaster3.setPreferredSize(new java.awt.Dimension(101, 32));
        cmdMaster3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdMaster3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdMaster3MouseExited(evt);
            }
        });
        cmdMaster3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMaster3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cmdMaster3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdMaster3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout spBgLayout = new javax.swing.GroupLayout(spBg);
        spBg.setLayout(spBgLayout);
        spBgLayout.setHorizontalGroup(
            spBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        spBgLayout.setVerticalGroup(
            spBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spBgLayout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 172, Short.MAX_VALUE))
        );

        scrollSide.setViewportView(spBg);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollSide, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(scrollSide, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        bg.add(sidePanel, java.awt.BorderLayout.LINE_START);

        topPanel.setBackground(new java.awt.Color(93, 239, 132));
        topPanel.setPreferredSize(new java.awt.Dimension(180, 25));
        topPanel.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("..:: Inventory Management System ::..");
        jLabel1.setPreferredSize(new java.awt.Dimension(225, 25));

        cmdExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\MOZART-PC\\Downloads\\close-window16.png")); // NOI18N
        cmdExit.setBorderPainted(false);
        cmdExit.setContentAreaFilled(false);
        cmdExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdExitMouseExited(evt);
            }
        });
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg.add(topPanel, java.awt.BorderLayout.PAGE_START);

        bgForm.setOpaque(false);

        subMaster.setBackground(new java.awt.Color(92, 121, 168));
        subMaster.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        subMaster.setAlignmentX(90.0F);
        subMaster.setAutoscrolls(true);
        subMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subMasterMouseExited(evt);
            }
        });

        mnuSupplier.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        mnuSupplier.setForeground(new java.awt.Color(255, 255, 255));
        mnuSupplier.setIcon(new javax.swing.ImageIcon("E:\\Source Code\\Icons_Images\\Image\\Supplier_32px.png")); // NOI18N
        mnuSupplier.setText("Supplier");
        mnuSupplier.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 2, 20));
        mnuSupplier.setContentAreaFilled(false);
        mnuSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mnuSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnuSupplier.setIconTextGap(40);
        mnuSupplier.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mnuSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuSupplierMouseExited(evt);
            }
        });

        mnuBarang.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        mnuBarang.setForeground(new java.awt.Color(255, 255, 255));
        mnuBarang.setIcon(new javax.swing.ImageIcon("E:\\Source Code\\Icons_Images\\Image\\Box Open_32.png")); // NOI18N
        mnuBarang.setText("Barang");
        mnuBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 2, 20));
        mnuBarang.setContentAreaFilled(false);
        mnuBarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mnuBarang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnuBarang.setIconTextGap(32);
        mnuBarang.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mnuBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuBarangMouseExited(evt);
            }
        });

        javax.swing.GroupLayout subMasterLayout = new javax.swing.GroupLayout(subMaster);
        subMaster.setLayout(subMasterLayout);
        subMasterLayout.setHorizontalGroup(
            subMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mnuBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
            .addComponent(mnuSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        subMasterLayout.setVerticalGroup(
            subMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMasterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mnuSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnuBarang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        subTrans.setBackground(new java.awt.Color(92, 121, 168));
        subTrans.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        subTrans.setAlignmentX(90.0F);
        subTrans.setAutoscrolls(true);
        subTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subTransMouseExited(evt);
            }
        });

        mnuSupplier1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        mnuSupplier1.setForeground(new java.awt.Color(255, 255, 255));
        mnuSupplier1.setIcon(new javax.swing.ImageIcon("E:\\Source Code\\Icons_Images\\Image\\Delivered_add-32.png")); // NOI18N
        mnuSupplier1.setText("Barang Masuk");
        mnuSupplier1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 2, 20));
        mnuSupplier1.setContentAreaFilled(false);
        mnuSupplier1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mnuSupplier1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnuSupplier1.setIconTextGap(40);
        mnuSupplier1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mnuSupplier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuSupplier1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuSupplier1MouseExited(evt);
            }
        });

        mnuBarang1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        mnuBarang1.setForeground(new java.awt.Color(255, 255, 255));
        mnuBarang1.setIcon(new javax.swing.ImageIcon("E:\\Source Code\\Icons_Images\\Image\\delivered_min_32.png")); // NOI18N
        mnuBarang1.setText("Barang Keluar");
        mnuBarang1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 2, 20));
        mnuBarang1.setContentAreaFilled(false);
        mnuBarang1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mnuBarang1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnuBarang1.setIconTextGap(40);
        mnuBarang1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mnuBarang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuBarang1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuBarang1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout subTransLayout = new javax.swing.GroupLayout(subTrans);
        subTrans.setLayout(subTransLayout);
        subTransLayout.setHorizontalGroup(
            subTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mnuBarang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
            .addComponent(mnuSupplier1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        subTransLayout.setVerticalGroup(
            subTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subTransLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mnuSupplier1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnuBarang1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgFormLayout = new javax.swing.GroupLayout(bgForm);
        bgForm.setLayout(bgFormLayout);
        bgFormLayout.setHorizontalGroup(
            bgFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgFormLayout.createSequentialGroup()
                .addComponent(subMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 375, Short.MAX_VALUE))
        );
        bgFormLayout.setVerticalGroup(
            bgFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgFormLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(bgFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        bg.add(bgForm, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void cmdExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdExitMouseEntered
        // TODO add your handling code here:
        cmdExit.setOpaque(true);
        cmdExit.setBackground(new Color(166, 237, 185));
    }//GEN-LAST:event_cmdExitMouseEntered

    private void cmdExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdExitMouseExited
        // TODO add your handling code here:
        cmdExit.setOpaque(false);
    }//GEN-LAST:event_cmdExitMouseExited

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cmdExitActionPerformed

    private void cmdMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMenuMouseEntered
        // TODO add your handling code here:
        cmdMenu.setOpaque(true);
        cmdMenu.setBackground(new Color(107, 132, 173));
    }//GEN-LAST:event_cmdMenuMouseEntered

    private void cmdMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMenuMouseExited
        // TODO add your handling code here:
        cmdMenu.setOpaque(false);
    }//GEN-LAST:event_cmdMenuMouseExited

    private void cmdMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMenuActionPerformed

    private void mnuSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSupplierMouseEntered
        // TODO add your handling code here:
        MouseHover(mnuSupplier);
    }//GEN-LAST:event_mnuSupplierMouseEntered

    private void mnuSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSupplierMouseExited
        // TODO add your handling code here:
        MouseExit(mnuSupplier);
    }//GEN-LAST:event_mnuSupplierMouseExited

    private void mnuBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBarangMouseEntered
        // TODO add your handling code here:
        MouseHover(mnuBarang);
    }//GEN-LAST:event_mnuBarangMouseEntered

    private void mnuBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBarangMouseExited
        // TODO add your handling code here:
        MouseExit(mnuBarang);
    }//GEN-LAST:event_mnuBarangMouseExited

    private void subMasterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMasterMouseExited
        // TODO add your handling code here:
        subMaster.setVisible(false);
    }//GEN-LAST:event_subMasterMouseExited

    private void cmdMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMasterActionPerformed
        // TODO add your handling code here:
        subMaster.setVisible(!subMaster.isVisible());
        subTrans.setVisible(false);
    }//GEN-LAST:event_cmdMasterActionPerformed

    private void cmdMasterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMasterMouseExited
        // TODO add your handling code here:
        MouseExit(cmdMaster);
    }//GEN-LAST:event_cmdMasterMouseExited

    private void cmdMasterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMasterMouseEntered
        // TODO add your handling code here:
        MouseHover(cmdMaster);
    }//GEN-LAST:event_cmdMasterMouseEntered

    private void cmdTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdTransaksiMouseEntered
        // TODO add your handling code here:
        MouseHover(cmdTransaksi);
    }//GEN-LAST:event_cmdTransaksiMouseEntered

    private void cmdTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdTransaksiMouseExited
        // TODO add your handling code here:
        MouseExit(cmdTransaksi);
    }//GEN-LAST:event_cmdTransaksiMouseExited

    private void cmdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTransaksiActionPerformed
        // TODO add your handling code here:
        subTrans.setLocation(subMaster.getLocation());
        subTrans.setVisible(!subTrans.isVisible());
        subMaster.setVisible(false);
    }//GEN-LAST:event_cmdTransaksiActionPerformed

    private void cmdMaster2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMaster2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMaster2MouseEntered

    private void cmdMaster2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMaster2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMaster2MouseExited

    private void cmdMaster2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMaster2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMaster2ActionPerformed

    private void mnuSupplier1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSupplier1MouseEntered
        // TODO add your handling code here:
        MouseHover(mnuSupplier1);
    }//GEN-LAST:event_mnuSupplier1MouseEntered

    private void mnuSupplier1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSupplier1MouseExited
        // TODO add your handling code here:
        MouseExit(mnuSupplier1);
    }//GEN-LAST:event_mnuSupplier1MouseExited

    private void mnuBarang1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBarang1MouseEntered
        // TODO add your handling code here:
        MouseHover(mnuBarang1);
    }//GEN-LAST:event_mnuBarang1MouseEntered

    private void mnuBarang1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBarang1MouseExited
        // TODO add your handling code here:
        MouseExit(mnuBarang1);
    }//GEN-LAST:event_mnuBarang1MouseExited

    private void subTransMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subTransMouseExited
        // TODO add your handling code here:
        subTrans.setVisible(!subTrans.isVisible());
    }//GEN-LAST:event_subTransMouseExited

    private void cmdMaster3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMaster3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMaster3MouseEntered

    private void cmdMaster3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMaster3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMaster3MouseExited

    private void cmdMaster3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMaster3ActionPerformed
        // TODO add your handling code here:
        clsConnection oConn=new clsConnection();
        try {
            if (oConn.getConnection()) {
                showMsg("Connected !", "Connection", 1);
                ResultSet rs = oConn.getData("Select user_name from t_user");
                while (rs.next()) {
                    showMsg(rs.getString("user_name"), "Info", 1);
                }
                oConn.disconnect();
            }
        } catch (Exception ex) {
            Logger.getLogger(frmUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdMaster3ActionPerformed
    
    private static void showMsg(String msg, String msgTitle, int msgType) {
        //0 = Error ; 1=Information ; 2 = Warning; 3 = Question
        JOptionPane.showMessageDialog(null, msg,msgTitle,msgType);
    }
    private void MouseHover(JButton obtn){
        obtn.setOpaque(true);
        obtn.setBackground(new Color(107, 132, 173));
        obtn.getParent().setVisible(true);
    }
    private void MouseExit(JButton obtn){
        obtn.setOpaque(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                clsConnection oConn = new clsConnection();
                if (oConn.getConnection()) {
                    new frmUtama().setVisible(true);   
                }
                else {
                    showMsg("Koneksi ke database gagal !", "Cek Koneksi", 2);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgForm;
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdMaster;
    private javax.swing.JButton cmdMaster2;
    private javax.swing.JButton cmdMaster3;
    private javax.swing.JButton cmdMenu;
    private javax.swing.JButton cmdTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton mnuBarang;
    private javax.swing.JButton mnuBarang1;
    private javax.swing.JButton mnuSupplier;
    private javax.swing.JButton mnuSupplier1;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JScrollPane scrollSide;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel spBg;
    private javax.swing.JPanel subMaster;
    private javax.swing.JPanel subTrans;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
