/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tgsUas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.LayoutManager;
import java.beans.PropertyVetoException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author MOZART-PC
 */
public class frmUtama extends javax.swing.JFrame {
    private clsMainFunction cls = new clsMainFunction();
    private JButton btnActive;
    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();
        subMaster.setVisible(false);
        subTrans.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        scrollSide = new javax.swing.JScrollPane();
        spBg = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmdMenu = new javax.swing.JButton();
        pnlMaster = new javax.swing.JPanel();
        cmdMaster = new javax.swing.JButton();
        pnlTrans = new javax.swing.JPanel();
        cmdTransaksi = new javax.swing.JButton();
        pnlLaporan = new javax.swing.JPanel();
        cmdLaporan = new javax.swing.JButton();
        subMaster = new javax.swing.JPanel();
        mnuSupplier = new javax.swing.JButton();
        mnuBarang = new javax.swing.JButton();
        subTrans = new javax.swing.JPanel();
        mnuBarangMasuk = new javax.swing.JButton();
        mnuBarangKeluar = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdExit = new javax.swing.JButton();
        Desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        bg.setMaximumSize(new java.awt.Dimension(32767, 100));
        bg.setPreferredSize(new java.awt.Dimension(728, 100));
        bg.setLayout(new java.awt.BorderLayout());

        sidePanel.setBackground(new java.awt.Color(92, 121, 168));
        sidePanel.setPreferredSize(new java.awt.Dimension(185, 395));

        scrollSide.setBackground(new java.awt.Color(92, 121, 168));
        scrollSide.setOpaque(false);

        spBg.setBackground(new java.awt.Color(27, 161, 226));
        spBg.setPreferredSize(new java.awt.Dimension(161, 400));

        pnlLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlLogo.setOpaque(false);
        pnlLogo.setPreferredSize(new java.awt.Dimension(174, 150));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tgsUas/Img/RnD-Logo150.png"))); // NOI18N

        cmdMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tgsUas/Img/Menu-16.png"))); // NOI18N
        cmdMenu.setBorderPainted(false);
        cmdMenu.setContentAreaFilled(false);
        cmdMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdMenuMouseExited(evt);
            }
        });
        cmdMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addComponent(cmdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        pnlMaster.setBackground(new java.awt.Color(27, 161, 226));

        cmdMaster.setBackground(new java.awt.Color(92, 121, 168));
        cmdMaster.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdMaster.setForeground(new java.awt.Color(255, 255, 255));
        cmdMaster.setText("Master Data");
        cmdMaster.setContentAreaFilled(false);
        cmdMaster.setPreferredSize(new java.awt.Dimension(101, 32));
        cmdMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdMasterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdMasterMouseExited(evt);
            }
        });
        cmdMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMasterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMasterLayout = new javax.swing.GroupLayout(pnlMaster);
        pnlMaster.setLayout(pnlMasterLayout);
        pnlMasterLayout.setHorizontalGroup(
            pnlMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMasterLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cmdMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMasterLayout.setVerticalGroup(
            pnlMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlTrans.setBackground(new java.awt.Color(27, 161, 226));

        cmdTransaksi.setBackground(new java.awt.Color(92, 121, 168));
        cmdTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        cmdTransaksi.setText("Transaksi");
        cmdTransaksi.setContentAreaFilled(false);
        cmdTransaksi.setPreferredSize(new java.awt.Dimension(101, 32));
        cmdTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdTransaksiMouseExited(evt);
            }
        });
        cmdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTransLayout = new javax.swing.GroupLayout(pnlTrans);
        pnlTrans.setLayout(pnlTransLayout);
        pnlTransLayout.setHorizontalGroup(
            pnlTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cmdTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTransLayout.setVerticalGroup(
            pnlTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlLaporan.setBackground(new java.awt.Color(27, 161, 226));

        cmdLaporan.setBackground(new java.awt.Color(92, 121, 168));
        cmdLaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdLaporan.setForeground(new java.awt.Color(255, 255, 255));
        cmdLaporan.setText("Laporan");
        cmdLaporan.setContentAreaFilled(false);
        cmdLaporan.setPreferredSize(new java.awt.Dimension(101, 32));
        cmdLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdLaporanMouseExited(evt);
            }
        });
        cmdLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLaporanLayout = new javax.swing.GroupLayout(pnlLaporan);
        pnlLaporan.setLayout(pnlLaporanLayout);
        pnlLaporanLayout.setHorizontalGroup(
            pnlLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLaporanLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cmdLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLaporanLayout.setVerticalGroup(
            pnlLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        subMaster.setBackground(new java.awt.Color(92, 121, 168));
        subMaster.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        subMaster.setAlignmentX(90.0F);
        subMaster.setAutoscrolls(true);
        subMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subMasterMouseExited(evt);
            }
        });

        mnuSupplier.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        mnuSupplier.setForeground(new java.awt.Color(255, 255, 255));
        mnuSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tgsUas/Img/Supplier_32px.png"))); // NOI18N
        mnuSupplier.setText("Supplier");
        mnuSupplier.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 2, 20));
        mnuSupplier.setContentAreaFilled(false);
        mnuSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mnuSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnuSupplier.setIconTextGap(40);
        mnuSupplier.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mnuSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuSupplierMouseExited(evt);
            }
        });
        mnuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSupplierActionPerformed(evt);
            }
        });

        mnuBarang.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        mnuBarang.setForeground(new java.awt.Color(255, 255, 255));
        mnuBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tgsUas/Img/Box Open_32.png"))); // NOI18N
        mnuBarang.setText("Barang");
        mnuBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 2, 20));
        mnuBarang.setContentAreaFilled(false);
        mnuBarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mnuBarang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnuBarang.setIconTextGap(32);
        mnuBarang.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mnuBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuBarangMouseExited(evt);
            }
        });
        mnuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subMasterLayout = new javax.swing.GroupLayout(subMaster);
        subMaster.setLayout(subMasterLayout);
        subMasterLayout.setHorizontalGroup(
            subMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mnuBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mnuSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        subMasterLayout.setVerticalGroup(
            subMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMasterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mnuSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnuBarang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        subTrans.setBackground(new java.awt.Color(92, 121, 168));
        subTrans.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        subTrans.setAlignmentX(90.0F);
        subTrans.setAutoscrolls(true);
        subTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subTransMouseExited(evt);
            }
        });

        mnuBarangMasuk.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        mnuBarangMasuk.setForeground(new java.awt.Color(255, 255, 255));
        mnuBarangMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tgsUas/Img/Delivered_add-32.png"))); // NOI18N
        mnuBarangMasuk.setText("Barang Masuk");
        mnuBarangMasuk.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 2, 20));
        mnuBarangMasuk.setContentAreaFilled(false);
        mnuBarangMasuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mnuBarangMasuk.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnuBarangMasuk.setIconTextGap(40);
        mnuBarangMasuk.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mnuBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuBarangMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuBarangMasukMouseExited(evt);
            }
        });
        mnuBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBarangMasukActionPerformed(evt);
            }
        });

        mnuBarangKeluar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        mnuBarangKeluar.setForeground(new java.awt.Color(255, 255, 255));
        mnuBarangKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tgsUas/Img/delivered_min_32.png"))); // NOI18N
        mnuBarangKeluar.setText("Barang Keluar");
        mnuBarangKeluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 2, 20));
        mnuBarangKeluar.setContentAreaFilled(false);
        mnuBarangKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mnuBarangKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mnuBarangKeluar.setIconTextGap(40);
        mnuBarangKeluar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mnuBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuBarangKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnuBarangKeluarMouseExited(evt);
            }
        });
        mnuBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBarangKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subTransLayout = new javax.swing.GroupLayout(subTrans);
        subTrans.setLayout(subTransLayout);
        subTransLayout.setHorizontalGroup(
            subTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mnuBarangKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mnuBarangMasuk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        subTransLayout.setVerticalGroup(
            subTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subTransLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mnuBarangMasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnuBarangKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout spBgLayout = new javax.swing.GroupLayout(spBg);
        spBg.setLayout(spBgLayout);
        spBgLayout.setHorizontalGroup(
            spBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
            .addComponent(pnlMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(spBgLayout.createSequentialGroup()
                .addGroup(spBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        spBgLayout.setVerticalGroup(
            spBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spBgLayout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        scrollSide.setViewportView(spBg);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(scrollSide, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollSide, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        bg.add(sidePanel, java.awt.BorderLayout.LINE_START);

        topPanel.setBackground(new java.awt.Color(93, 239, 132));
        topPanel.setPreferredSize(new java.awt.Dimension(180, 25));
        topPanel.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("..:: Inventory Management System ::..");
        jLabel1.setPreferredSize(new java.awt.Dimension(225, 25));

        cmdExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tgsUas/Img/close-window16.png"))); // NOI18N
        cmdExit.setBorderPainted(false);
        cmdExit.setContentAreaFilled(false);
        cmdExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdExitMouseExited(evt);
            }
        });
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg.add(topPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        bg.add(Desktop, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void menuActive(JButton obj) {
        if (btnActive==obj) {
            btnActive=null;
            return;
        }
        btnActive=obj;
        if (obj==cmdMaster) {
            ExitMenu(cmdTransaksi);
            ExitMenu(cmdLaporan);
        }
        if (obj==cmdTransaksi) {
            ExitMenu(cmdMaster);
            ExitMenu(cmdLaporan);
        }
        if (obj==cmdLaporan) {
            ExitMenu(cmdTransaksi);
            ExitMenu(cmdMaster);
        }
    }
    private void HoverMenu(JButton obj) {
        obj.setBackground(new Color(213, 229, 226));
        obj.setForeground(Color.black);
        obj.setOpaque(true);
        obj.getParent().setBackground(Color.green);
    }
    
    private void ExitMenu(JButton obj) {
        if (btnActive==obj) {
            return;
        }
        obj.setForeground(Color.white);
        obj.setOpaque(false);
        obj.getParent().setBackground(obj.getParent().getParent().getBackground());
    }
    private void cmdExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdExitMouseEntered
        // TODO add your handling code here:
        cmdExit.setOpaque(true);
        cmdExit.setBackground(new Color(166, 237, 185));
    }//GEN-LAST:event_cmdExitMouseEntered

    private void cmdExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdExitMouseExited
        // TODO add your handling code here:
        cmdExit.setOpaque(false);
    }//GEN-LAST:event_cmdExitMouseExited

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cmdExitActionPerformed
    
    private void cmdMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMenuMouseEntered
        // TODO add your handling code here:
        //cmdMenu.setOpaque(true);
        //cmdMenu.setBackground(new Color(107, 132, 173));
        HoverMenu(cmdMenu);
    }//GEN-LAST:event_cmdMenuMouseEntered

    private void cmdMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMenuMouseExited
        // TODO add your handling code here:
        //cmdMenu.setOpaque(false);
        ExitMenu(cmdMenu);
    }//GEN-LAST:event_cmdMenuMouseExited

    private void cmdMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMenuActionPerformed

    private void cmdMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMasterActionPerformed
        // TODO add your handling code here:
        menuActive(cmdMaster);
        subMaster.setVisible(!subMaster.isVisible());
        subTrans.setVisible(false);
    }//GEN-LAST:event_cmdMasterActionPerformed

    private void cmdMasterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMasterMouseExited
        // TODO add your handling code here:
        ExitMenu(cmdMaster);
    }//GEN-LAST:event_cmdMasterMouseExited

    private void cmdMasterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMasterMouseEntered
        // TODO add your handling code here:
        HoverMenu(cmdMaster);
    }//GEN-LAST:event_cmdMasterMouseEntered

    private void cmdTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdTransaksiMouseEntered
        // TODO add your handling code here:
        HoverMenu(cmdTransaksi);
    }//GEN-LAST:event_cmdTransaksiMouseEntered

    private void cmdTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdTransaksiMouseExited
        // TODO add your handling code here:
        ExitMenu(cmdTransaksi);
    }//GEN-LAST:event_cmdTransaksiMouseExited

    private void cmdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTransaksiActionPerformed
        // TODO add your handling code here:
        menuActive(cmdTransaksi);
        subTrans.setLocation(subMaster.getLocation());
        subTrans.setVisible(!subTrans.isVisible());
        subMaster.setVisible(false);
    }//GEN-LAST:event_cmdTransaksiActionPerformed

    private void cmdLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdLaporanMouseEntered
        // TODO add your handling code here:
        HoverMenu(cmdLaporan);
    }//GEN-LAST:event_cmdLaporanMouseEntered

    private void cmdLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdLaporanMouseExited
        // TODO add your handling code here:
        ExitMenu(cmdLaporan);
    }//GEN-LAST:event_cmdLaporanMouseExited

    private void cmdLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLaporanActionPerformed
        // TODO add your handling code here:
        menuActive(cmdLaporan);
        laporan_Inventory obj = new laporan_Inventory();
        showMenu(obj);
    }//GEN-LAST:event_cmdLaporanActionPerformed

    private void subTransMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subTransMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_subTransMouseExited

    private void mnuBarangKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBarangKeluarMouseExited
        // TODO add your handling code here:
        MouseExit(mnuBarangKeluar);
    }//GEN-LAST:event_mnuBarangKeluarMouseExited

    private void mnuBarangKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBarangKeluarMouseEntered
        // TODO add your handling code here:
        MouseHover(mnuBarangKeluar);
    }//GEN-LAST:event_mnuBarangKeluarMouseEntered

    private void mnuBarangMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBarangMasukMouseExited
        // TODO add your handling code here:
        MouseExit(mnuBarangMasuk);
    }//GEN-LAST:event_mnuBarangMasukMouseExited

    private void mnuBarangMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBarangMasukMouseEntered
        // TODO add your handling code here:
        MouseHover(mnuBarangMasuk);
    }//GEN-LAST:event_mnuBarangMasukMouseEntered

    private void subMasterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMasterMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_subMasterMouseExited

    private void mnuBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBarangMouseExited
        // TODO add your handling code here:
        MouseExit(mnuBarang);
    }//GEN-LAST:event_mnuBarangMouseExited

    private void mnuBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBarangMouseEntered
        // TODO add your handling code here:
        MouseHover(mnuBarang);
    }//GEN-LAST:event_mnuBarangMouseEntered

    private void mnuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSupplierActionPerformed
        // TODO add your handling code here:
        master_Supplier obj = new master_Supplier();
        showMenu(obj);
    }//GEN-LAST:event_mnuSupplierActionPerformed

    private void mnuSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSupplierMouseExited
        // TODO add your handling code here:
        MouseExit(mnuSupplier);
    }//GEN-LAST:event_mnuSupplierMouseExited

    private void mnuSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSupplierMouseEntered
        // TODO add your handling code here:
        MouseHover(mnuSupplier);
    }//GEN-LAST:event_mnuSupplierMouseEntered

    private void mnuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBarangActionPerformed
        // TODO add your handling code here:
        master_Barang obj = new master_Barang();
        showMenu(obj);
    }//GEN-LAST:event_mnuBarangActionPerformed

    private void mnuBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBarangMasukActionPerformed
        // TODO add your handling code here:
        transaksi_Masuk frm = new transaksi_Masuk();
        showMenu(frm);
    }//GEN-LAST:event_mnuBarangMasukActionPerformed

    private void mnuBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBarangKeluarActionPerformed
        // TODO add your handling code here:
        transaksi_Keluar frm = new transaksi_Keluar();
        showMenu(frm);
    }//GEN-LAST:event_mnuBarangKeluarActionPerformed
    
    private void MouseHover(JButton obtn){
        obtn.setOpaque(true);
        obtn.setBackground(new Color(107, 132, 173));
        obtn.getParent().setVisible(true);
    }
    private void MouseExit(JButton obtn){
        obtn.setOpaque(false);
    }
    
    public void showMenu(JInternalFrame frm) {
        boolean loaded=false;
        JInternalFrame existingFrame[] = Desktop.getAllFrames();
        int i=1;
        for (i=1;i<=existingFrame.length;i++) {
            if (existingFrame[i-1].getClass()==frm.getClass()) {
                loaded=true;
                i=i-1;
                break;
            }
        }
        if (!loaded) {
            //Convert JInternalFrame to BasicInternalFrame so the frame can 
            //be maximized
            ((BasicInternalFrameUI)frm.getUI()).setNorthPane(null);
            Desktop.add(frm);
            frm.setVisible(true);
            try {
                frm.setMaximum(true);  //set frame to maximized here
            } catch (PropertyVetoException e) {
                cls.showMsg("Show Menu Error !", "showMenu", 2);
            }
        }
        else {
            existingFrame[i].toFront();
            try {
                (existingFrame[i]).setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(frmUtama.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUtama().setVisible(true);   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JPanel bg;
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdLaporan;
    private javax.swing.JButton cmdMaster;
    private javax.swing.JButton cmdMenu;
    private javax.swing.JButton cmdTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mnuBarang;
    private javax.swing.JButton mnuBarangKeluar;
    private javax.swing.JButton mnuBarangMasuk;
    private javax.swing.JButton mnuSupplier;
    private javax.swing.JPanel pnlLaporan;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlMaster;
    private javax.swing.JPanel pnlTrans;
    private javax.swing.JScrollPane scrollSide;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel spBg;
    private javax.swing.JPanel subMaster;
    private javax.swing.JPanel subTrans;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
