/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tgsUas;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MOZART-PC
 */
public class laporanInventory extends javax.swing.JInternalFrame {
    clsMainFunction cls = new clsMainFunction();
    clsConnection oConn = new clsConnection();
    /**
     * Creates new form laporanInventory
     */
    public laporanInventory() {
        initComponents();
        cmdDisplay1.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cmdDisplay1 = new javax.swing.JButton();
        txtDari = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSampai = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cmdClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        bg.setBackground(new java.awt.Color(27, 161, 226));
        bg.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(639, 75));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdDisplay1.setBackground(new java.awt.Color(255, 255, 255));
        cmdDisplay1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmdDisplay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tgsUas/Img/search.png"))); // NOI18N
        cmdDisplay1.setText("Tampilkan Data");
        cmdDisplay1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        cmdDisplay1.setContentAreaFilled(false);
        cmdDisplay1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmdDisplay1.setMaximumSize(new java.awt.Dimension(87, 21));
        cmdDisplay1.setMinimumSize(new java.awt.Dimension(87, 21));
        cmdDisplay1.setPreferredSize(new java.awt.Dimension(87, 21));
        cmdDisplay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdDisplay1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdDisplay1MouseExited(evt);
            }
        });
        cmdDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDisplay1ActionPerformed(evt);
            }
        });
        jPanel4.add(cmdDisplay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 120, -1));

        txtDari.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtDari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDariKeyPressed(evt);
            }
        });
        jPanel4.add(txtDari, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 22));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setText("Cari Laporan berdasarkan periode. Format tanggal yyyy-mm-dd. Contoh : 2017-01-31");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtSampai.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtSampai.setMaximumSize(new java.awt.Dimension(59, 21));
        txtSampai.setMinimumSize(new java.awt.Dimension(59, 21));
        txtSampai.setPreferredSize(new java.awt.Dimension(59, 21));
        jPanel4.add(txtSampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 140, 22));

        bg.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(803, 50));

        cmdClose.setBackground(new java.awt.Color(255, 255, 255));
        cmdClose.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tgsUas/Img/Close_16.png"))); // NOI18N
        cmdClose.setText("Keluar");
        cmdClose.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        cmdClose.setContentAreaFilled(false);
        cmdClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmdClose.setMaximumSize(new java.awt.Dimension(87, 27));
        cmdClose.setMinimumSize(new java.awt.Dimension(87, 27));
        cmdClose.setPreferredSize(new java.awt.Dimension(87, 27));
        cmdClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmdCloseMouseExited(evt);
            }
        });
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(720, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(cmdClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLaporan);

        bg.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdDisplay1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdDisplay1MouseEntered
        // TODO add your handling code here:
        cls.HoverButton(cmdDisplay1);
    }//GEN-LAST:event_cmdDisplay1MouseEntered

    private void cmdDisplay1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdDisplay1MouseExited
        // TODO add your handling code here:
        cls.ExitButton(cmdDisplay1);
    }//GEN-LAST:event_cmdDisplay1MouseExited

    private void cmdDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDisplay1ActionPerformed
        try {
            Date date=new Date();
            SimpleDateFormat parser = new SimpleDateFormat("yyyy-M-dd");
            if (txtDari.getText().equals("")) {
                txtDari.setText(parser.format(date));
            }
            if (txtSampai.getText().equals("")) {
                txtSampai.setText(parser.format(date));
            }
            
            try {
                Date sDate=parser.parse(txtDari.getText());
                Date eDate=parser.parse(txtSampai.getText());
                // TODO add your handling code here:
                String str="select barang_kode as 'Kode Barang', barang_nama as 'Nama Barang', "
                        + "no_rak as 'No. Rak', beg as 'Qty Awal', in_qty as 'Qty Masuk', out_qty as 'Qty Keluar', "
                        + "ifnull(beg,0) + ifnull(in_qty,0) + ifnull(out_qty,0) as 'Qty Akhir' from t_barang brg left join "
                        + "(select barang_kode as kode, sum(inv_qty) as beg from t_inventory "
                        + "where inv_tgl < '"+ sDate +" 00:00:00') beg on barang_kode = kode "
                        + "LEFT JOIN (select barang_kode as kode, sum(inv_qty) as in_qty, from t_inventory where "
                        + "inv_tgl between '"+ sDate +" 00:00:00' and '"+ eDate +" 00:00:00' "
                        + "and inv_qty > 0) inv_in on barang_kode = inv_in.kode LEFT JOIN ("
                        + "select barang_kode as kode, sum(inv_qty) as out_qty from t_inventory where "
                        + "inv_tgl between '"+ sDate +" 00:00:00' and '"+ eDate +" 00:00:00' and inv_qty < 0"
                        + ") inv_out on barang_kode = inv_in.kode";
                cls.showTblGrid(tblLaporan, str);
            } catch (ParseException ex) {
                Logger.getLogger(laporanInventory.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            tblLaporan.setEditingColumn(0);
            tblLaporan.setEditingRow(0);
        } catch (SQLException ex) {
            cls.showMsg(ex.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_cmdDisplay1ActionPerformed

    private void txtDariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDariKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            cmdDisplay1.doClick();
        }
    }//GEN-LAST:event_txtDariKeyPressed

    private void cmdCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdCloseMouseEntered
        // TODO add your handling code here:
        cls.HoverButton(cmdClose);
    }//GEN-LAST:event_cmdCloseMouseEntered

    private void cmdCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdCloseMouseExited
        // TODO add your handling code here:
        cls.ExitButton(cmdClose);
    }//GEN-LAST:event_cmdCloseMouseExited

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmdCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdDisplay;
    private javax.swing.JButton cmdDisplay1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLaporan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtDari;
    private javax.swing.JTextField txtSampai;
    // End of variables declaration//GEN-END:variables
}
